on:
  workflow_dispatch:
  push:
    branches:
        - development
env:
  NODE_VERSION: '20.x'  

jobs:
  build_and_deploy:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v1

      - name: Print
        run: dir 

      - name: Build application
        working-directory: ./MohaQuiz.Frontend
        run: npm ci && npm run build --output-path=dist && dir

      - name: Deploy to Simply
        uses: jahbenjah/SmarterASP.NET-web-deploy@1.0.0.alpha.8
        with:
          website-name: ${{ secrets.WEBSITE_NAME }}
          server-computer-name: ${{ secrets.SERVER_COMPUTER_NAME }}
          server-username: ${{ secrets.SERVER_USERNAME }}
          server-password: ${{ secrets.SERVER_PASSWORD }}
          source-path: 'MohaQuiz.Frontend/dist/MohaQuiz.Frontend/'
          target-path: /wwwroot/
          target-delete: false
